[project]
name = "procrustes-annotator"
version = "0.1.0"
description = "Interactive RGB-D correspondence annotation and Procrustes pose solving"
readme = "README.md"
requires-python = "==3.12.*"
dependencies = [
    "numpy>=2.0",
    "Pillow>=10.0",
    "PySide6>=6.8",
    "pyvista>=0.48",
    "pyvistaqt>=0.11",
    "opencv-python",
    "open3d"

]

[project.scripts]
procrustes-annotator = "src.frontend.main:main"

[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["src*"]
